# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pj < Formula
  desc "Fast project finder CLI that searches your filesystem for git repositories and project directories"
  homepage "https://github.com/josephschmitt/pj"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephschmitt/pj/releases/download/v1.4.0/pj_1.4.0_darwin_amd64.tar.gz"
      sha256 "206ff0248dc39689f35741928e782875d2d0e6b25db8223ffe77a0e208f0a01d"

      def install
        bin.install "pj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephschmitt/pj/releases/download/v1.4.0/pj_1.4.0_darwin_arm64.tar.gz"
      sha256 "7fcdfcc014d4869565c90576d020e17349b485893aa2d994aa087f74dcbdaf8b"

      def install
        bin.install "pj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/pj/releases/download/v1.4.0/pj_1.4.0_linux_amd64.tar.gz"
      sha256 "0edb9bc46db69cf4354f9d8bc6af14e74c4d2788d9acb23aa9be9cab6d2f97df"
      def install
        bin.install "pj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/pj/releases/download/v1.4.0/pj_1.4.0_linux_arm64.tar.gz"
      sha256 "0099beaff44f4704b9e3737682d83cf3642051f70729b61cf360da348cfca87c"
      def install
        bin.install "pj"
      end
    end
  end

  test do
    system "#{bin}/pj", "--version"
  end
end
