# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pj < Formula
  desc "Fast project finder CLI that searches your filesystem for git repositories and project directories"
  homepage "https://github.com/josephschmitt/pj"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephschmitt/pj/releases/download/v1.1.0/pj_1.1.0_darwin_amd64.tar.gz"
      sha256 "de23ed7afb36421e8ad4d97e828df98934ac289ae15120d612f031703bcc8ff7"

      def install
        bin.install "pj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephschmitt/pj/releases/download/v1.1.0/pj_1.1.0_darwin_arm64.tar.gz"
      sha256 "f47b11bee21d505d3b8dbc04de8a105f1f1a589f5f54c6b961dfc52a240559e9"

      def install
        bin.install "pj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/pj/releases/download/v1.1.0/pj_1.1.0_linux_amd64.tar.gz"
      sha256 "f890176cc6453e50683e85243f708a4e58668cbe9292616be90a25eb9366913d"
      def install
        bin.install "pj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/pj/releases/download/v1.1.0/pj_1.1.0_linux_arm64.tar.gz"
      sha256 "d1372c698a4a89d411f9d8a69230d594df31932b4634a70a1a3e46301f7dcc27"
      def install
        bin.install "pj"
      end
    end
  end

  test do
    system "#{bin}/pj", "--version"
  end
end
